### ISSUE TITLE
Enhancement: Additional Gag Multiplier For Boss Fights

### ISSUE THREAD

**Issue by Tree52** [zzzachzzz/toontown-combos#34]
Hey, thanks for this project; it's really useful.

Something like this would be nice:

![Screenshot 2024-08-07 174052](https://github.com/user-attachments/assets/f74816e5-0db8-4599-a3ad-92b4a53504da)

**Comment by zzzachzzz** [comment]
Agreed! I'll see what I can do

**Comment by zzzachzzz** [comment]
@Tree52 Would the damage calculation for these bonuses be applied to the sum of damage dealt for a given gag track? For example lets say 2 toons use throw and 2 toons use squirt in one round on a lured cog. Would the calc look like this:

"sum of throw damage including same type bonus and lure bonus" * "additional gag multiplier"
+
"sum of squirt damage including same type bonus" * "additional gag multiplier"

**Comment by zzzachzzz** [comment]
@Tree52 Thanks for the thorough report. I'm confused by some of the apparent inconsistencies in how the damage is calculated.

In example 1, the decreased defense **does not** seem to impact the base damages, rather it affects the multiplier in the knockback stage.

Yet in examples 2 and 3, the increased defense **does** impact the base damages.

Is there a pattern you're seeing that provides an explanation? I wonder if these differences are intentional or bugged? Are these videos all current, to rule out the explanation of one result being pre-bugfix and another being post-bugfix?

**Comment by zzzachzzz** [comment]
Completed by #37
